stages:
- name: build
  steps:
  - runScriptConfig:
      image: golang:latest
      shellScript: "1"
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: qq873241789/tyls
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
